apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: thienyet1011/gitops:55f807c75a4a0b86c1a05336b97d06f66bbca74a
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-cr-secret
