apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: ghcr.io/ghcr.io/thienyet1011/gitops:f653aa1e3de5890b01587fdd0547d059d22b673c
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-cr-secret
